# Generated by Django 4.1.2 on 2022-10-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_featured",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="is featured"
            ),
        ),
    ]
