# Generated by Django 4.1.2 on 2022-10-20 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_article_is_featured"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="title"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        max_length=300,
                        upload_to="articles/images/%Y/%m",
                        verbose_name="image",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="articles.article",
                        verbose_name="article",
                    ),
                ),
            ],
            options={
                "verbose_name": "article image",
                "verbose_name_plural": "article images",
            },
        ),
    ]
