# Generated by Django 4.1.2 on 2022-10-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_articleimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="view_count",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="view count"
            ),
        ),
    ]
